#pragma kernel CSMain

#define thread_group_x 2
#define thread_group_y 2
#define thread_x 2
#define thread_y 2
 
RWStructuredBuffer<float3> Result;
RWStructuredBuffer<float3> preVertices;
RWStructuredBuffer<float3> nextVertices;

//单个线程组包含的线程数
[numthreads(2,2,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int index = id.x + (id.y * thread_x * thread_group_x) + (id.z * thread_group_x * thread_group_y * thread_x * thread_y);
    Result[index] = preVertices[index] + nextVertices[index];
}
